(define a 1)
(define b (- 2))
(+ a 3 6 (- 7 8) -6)
(quotient a 3)
(remainder a 3)
(max a 3 7 4)
(min a 3 7 4)
(expt 3 4)
(sqrt 9)
(define str "hello world")
(define true #t)
(if (= a 5)
    (* a 5)
    (/ a 5))
(cond ((= a 5) #t)
      ((> a 5) "larger")
      (else "smaller"))
(zero? a)
(= a 1)
(eqv? "hello" "hello")
(define (f a b)
  (+ a (* 2 b)))
(f 2 4)
(and (= a 1) (> 2 4))
(or (= a 1) (> 2 4))
(not (= a 1))